apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: melikost-prometheus
  namespace: fury-melikost
spec:
  values:
    prometheusOperator:
      enabled: true
      resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 100Mi