apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: melikost-redis
  namespace: fury-melikost
spec:
  values:
    global:
      storageClass: "standard" # faster-storage on AWS
      redis:
        password: "melikost"
    master:
      count: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 333m
          memory: 1Gi