apiVersion: v1
kind: Service
metadata:
  name: melikost-extractor
  namespace: melikost
  labels:
    app: melikost-extractor
    app.kubernetes.io/name: melikost-extractor
    app.kubernetes.io/instance: melikost
    app.kubernetes.io/version: 2.2.3
    app.kubernetes.io/component: extractor
    app.kubernetes.io/part-of: melikost
spec:
  selector:
    app: melikost-extractor
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP