apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: melikost-prometheus
  namespace: fury-melikost
spec:
  values:
    prometheusOperator:
      enabled: true
      resources:
        limits:
          cpu: 1000m
          memory: 2000Mi
        requests:
          cpu: 500m
          memory: 1000Mi