apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: melikost-redis
  namespace: fury-melikost
spec:
  interval: 1m
  releaseName: melikost-redis
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: melikost-redis
        namespace: fury-melikost
      version: "20.0.3"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      storageClass: "faster-storage" # faster-storage on AWS
      redis:
        password: "melikost"
    master:
      count: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 2Gi
    replica:
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 2Gi