apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: melikost-prometheus
  namespace: fury-melikost
spec:
  interval: 3m
  url: https://prometheus-community.github.io/helm-charts