apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fury-melikost-redis
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: fury-melikost
  sourceRef:
    kind: GitRepository
    name: fury-serverless-specs-base
    namespace: flux-system
  path: "./apps/fury-melikost/redis/overlays/dev"
  prune: true
  timeout: 1m0s
