apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: melikost-prometheus-adapter
  namespace: fury-melikost
spec:
  releaseName: melikost-prometheus-adapter
  chart:
    spec:
      chart: prometheus-adapter
      sourceRef:
        kind: HelmRepository
        name: melikost-prometheus
        namespace: fury-melikost
      version: 4.10.0
  interval: 1m
  values:
    logLevel: 1
    prometheus:
      url: http://melikost-prometheus-prometheus.fury-melikost.svc
    rules:
      custom:
        - metricsQuery: (sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>))
          name:
            as: "${1}_nsq_messages_queued"
            matches: ^(.*)_nsq_channel_depth
          resources:
            overrides:
              namespace:
                resource: namespace
              pod:
                resource: pod
              service:
                resource: service
          seriesQuery: melikost_nsq_channel_depth{job="nsq-metrics"}
      default: false